### ISSUE TITLE
Video List

### ISSUE THREAD

**Issue by dkuc** [dkuc/shadowclip-web#2]
A paginated list of videos
Requirements:

- A search bar for video title

For each video
1. Video Title
2. Thumbnail
3. Date Uploaded
4. Size
5. Delete button(only shown if video owner)
6. Uploaded by hash

See https://shadowclip.net/videos

**Comment by dkuc** [comment]
A paginated list of videos
Requirements:

- A search bar for video title

For each video
1. Video Title
2. Thumbnail
3. Date Uploaded
4. Size
5. Delete button(only shown if video owner)
6. Uploaded by hash

See https://shadowclip.net/videos

**Comment by ryelo** [comment]
does this have to be paginated? Was thinking about moving it to a virtualized table with infinite scroll

**Comment by dkuc** [comment]
I'd prefer paginated, but if its way easier, infinite scroll is acceptable.
